# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/practice_deep_learning',
                'doc_host': 'https://arun477.github.io',
                'git_url': 'https://github.com/arun477/practice_deep_learning',
                'lib_path': 'practice_deep_learning'},
  'syms': {'practice_deep_learning.core': {'practice_deep_learning.core.foo': ('core.html#foo', 'practice_deep_learning/core.py')}}}
