# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/practice_deep_learning',
                'doc_host': 'https://arun477.github.io',
                'git_url': 'https://github.com/arun477/practice_deep_learning',
                'lib_path': 'practice_deep_learning'},
  'syms': { 'practice_deep_learning.training': { 'practice_deep_learning.training.Dataset': ( 'mini_batch_training.html#dataset',
                                                                                              'practice_deep_learning/training.py'),
                                                 'practice_deep_learning.training.Dataset.__getitem__': ( 'mini_batch_training.html#dataset.__getitem__',
                                                                                                          'practice_deep_learning/training.py'),
                                                 'practice_deep_learning.training.Dataset.__init__': ( 'mini_batch_training.html#dataset.__init__',
                                                                                                       'practice_deep_learning/training.py'),
                                                 'practice_deep_learning.training.Dataset.__len__': ( 'mini_batch_training.html#dataset.__len__',
                                                                                                      'practice_deep_learning/training.py'),
                                                 'practice_deep_learning.training.fit': ( 'mini_batch_training.html#fit',
                                                                                          'practice_deep_learning/training.py'),
                                                 'practice_deep_learning.training.get_dls': ( 'mini_batch_training.html#get_dls',
                                                                                              'practice_deep_learning/training.py')}}}
