# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_learner.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/09_learner.ipynb 1
import torch
import matplotlib.pyplot as plt
from torch import tensor
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms.functional as TF
from datasets import load_dataset
import fastcore.all as fc
from torch.utils.data import DataLoader
from .conv import *
